### ISSUE TITLE
4" Container leaking

### ISSUE THREAD

**Issue by yuanagain** [AmericanMarineResearch/development#2]

**Comment by Zack-P** [comment]
During testing at Fort Pickens we noticed a leak in the electronics housing. The leak appeared to happen around 20ft deep. After inspecting the housing I found that the leak was due to a faulty O-Ring located between the flange and the perpetrator bulkhead. I replaced the faulty O-Ring, as well as, all the perpetrator o-rings. After replacing the o-rings I pressure tested the electronics housing for 10 min at a negative pressure of -15 mmHG. All issues with the leak have been resolved.
